apiVersion: v1
kind: Service
metadata:
  name: helloworld-app
  namespace: tfe
spec:
  type: NodePort
  selector:
    app: helloworld-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081