apiVersion: v1
kind: Service
metadata:
  name: helloworld-app
  namespace: tfe
spec:
  type: NodePort
  selector:
    app: helloworld-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081