apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-helloworld-ingress
  namespace: tfe
spec:
  ingressClassName: nginx
  rules:
    - host: keycloak.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080

    - host: api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: helloworld-app-service
                port:
                  number: 8080
