apiVersion: v1
kind: Pod
metadata:
  name: keycloak
  namespace: tfe
  labels:
    app: keycloak
spec:
  containers:
    - name: keycloak
      image: quay.io/keycloak/keycloak:26.5.1
      args:
        - start-dev
      ports:
        - containerPort: 8080
      env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: admin
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: admin
        - name: KC_HOSTNAME
          value: keycloak.local
        - name: KC_HOSTNAME_PORT
          value: "30083"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_PROXY
          value: edge